apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ['-c', 'X=1; while [ $X -lt 1000000000 ];do echo "$X"; X+=1; sleep 1; done']
