apiVersion: v1
kind: Service
metadata:
  name: satisfactory
spec:
  selector:
    app: Satisfactory-Pod-Label
  ports:
    - name: tcp-port
      port: 7777
      targetPort: 7777
      nodePort: 30003
      protocol: TCP
    - name: udp-port
      port: 7777
      targetPort: 7777
      nodePort: 30003
      protocol: UDP
  type: NodePort
