# run `kubectl apply -f ./pod.yaml`
# kubectl delete pod minecraft-java

apiVersion: v1
kind: Pod
metadata:
  name: minecraft-java
  labels:
    app: minecraft-java
spec:
  containers:
  - name: minecraft-java 
    image: itzg/minecraft-server
    env:
    - name: EULA
      value: "TRUE"
    ports:
    - containerPort: 25565    
    volumeMounts: 
      - mountPath: /data
        name: minecraft-storage
  volumes:
    - name: minecraft-storage
      persistentVolumeClaim:
        claimName: pvc-1

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-java
spec:
  type: NodePort
  selector:
    app: minecraft-java
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30001 
