apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /mnt/data/pv-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: game-servers
