# to make this deployment available in an arbitrary namespace x execute
# kubectl apply -f ./deployment.yaml --namespace=x
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-d
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels: # others like service.yaml can try matching against this label with selector
    # TODO what is the difference to deployment.yaml.spec.template.metadata.labels?
      app: mongodb
  template:
    metadata:
      labels: # key value pairs in here are matched by key value pairs in service.yaml.spec.selector
        app: mongodb
    spec:
      containers:
      - name: mongodb-cont
        image: mongo # https://hub.docker.com/_/mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-sec # is matched against secret.yaml.metadata.name
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-sec # is matched against secret.yaml.metadata.name
              key: mongo-root-password


