# to make these secrets available in an arbitrary namspace x execute
# kubectl apply -f ./secret.yaml --namespace=x
# read https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-sec
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
