apiVersion: v1
kind: Service
metadata:
  name: mongodb-s
spec:
  selector: # for connecting to containers via deployment.yaml.spec.template.label
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017 # port exposed by the service
    targetPort: 27017 # port exposed by pod to service
