# to make this service available in an arbitrary namspace x execute
# kubectl apply -f ./service.yaml --namespace=x
apiVersion: v1
kind: Service
metadata:
  name: mongodb-s
spec:
  selector: # key value pairs in here are matched by key value pairs in deployment.yaml.spec.template.label
    app: mongodb
# spec.type: ClusterIP # is default for spec.type
  ports:
  - protocol: TCP
    port: 27017 # port exposed by the service
    targetPort: 27017 # port exposed by pod to service
