apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-i
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend: # sub directory name so e.g. myapp.com/backend/ would be what you would enter into the browser
            service:
              name: nginx-s # refers to metadata.name of an internal service
              port:
                number: 80 # refers to spec.ports.port of the selected service
