# to make this service available in an arbitrary namspace x execute
# kubectl apply -f ./service.yaml --namespace=x
apiVersion: v1
kind: Service
metadata:
  name: nginx-s
spec:
  selector:
    app: nginx.l
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

