# to make this deployment available in an arbitrary namspace x execute
# kubectl apply -f ./deployment.yaml --namespace=x
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-d
  labels:
   app: mongodb-express-l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express-l
  template:
    metadata:
      labels:
        app: mongodb-express-l
    spec:
      containers:
      - name: mongodb-express-cont
        image: mongo-express # https://hub.docker.com/_/mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-sec
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-sec
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-c
              key: database_url
