# https://kubernetes.io/docs/concepts/services-networking/gateway/

# a gateway in the request flow
#                                                                                             ┌───┐
#  ┌──────┐    http request    ┌─────────────┐   ┌─────────┐    routing rule    ┌───────┐ ┌──►│pod│
#  │client├───────────────────►│Gateway-stuff┼──►│HTTPRoute├───────────────────►│Service├─┤   └───┘
#  └──────┘                    └─────────────┘   └─────────┘                    └───────┘ │   ┌───┐
#                                                                                         └──►│pod│
#                                                                                             └───┘
# the Gateway-stuff us made up of a gateway-class which defines a controller
# which has to exist thats why it is required to run
#   kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/release-1.29/examples/gateway/00-crds.yaml
# and read
#   https://projectcontour.io/docs/1.29/guides/gateway-api/
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mongodb-express-gateway
spec:
  gatewayClassName: mongodb-express-gateway-class # references the gatewayClasses metadata.name
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
